import re


class CitationValidator:
    """
    Validates citation references generated by the LLM.

    A citation is valid only if its ID exists in the
    citation metadata provided to the validator.
    """

    CITATION_PATTERN = re.compile(
        r"\[(\d+)\]"
    )

    # =========================================================
    # VALIDATE
    # =========================================================

    def validate(
        self,
        answer: str,
        citations: list[dict],
    ):
        """
        Validate citation IDs used inside the answer.

        Returns:

            valid_citations
            invalid_citations
        """

        # -----------------------------------------------------
        # Extract citation IDs from answer
        # -----------------------------------------------------

        citation_ids = self.extract_citation_ids(
            answer
        )

        # -----------------------------------------------------
        # Create lookup of available citations
        # -----------------------------------------------------

        available_ids = {
            citation["id"]
            for citation in citations
        }

        # -----------------------------------------------------
        # Determine valid / invalid IDs
        # -----------------------------------------------------

        valid_ids = [
            citation_id
            for citation_id in citation_ids
            if citation_id in available_ids
        ]

        invalid_ids = [
            citation_id
            for citation_id in citation_ids
            if citation_id not in available_ids
        ]

        # -----------------------------------------------------
        # Return citation metadata
        # -----------------------------------------------------

        valid_citations = [
            citation
            for citation in citations
            if citation["id"] in valid_ids
        ]

        return (
            valid_citations,
            invalid_ids,
        )

    # =========================================================
    # EXTRACT CITATION IDS
    # =========================================================

    @classmethod
    def extract_citation_ids(
        cls,
        answer: str,
    ) -> list[int]:
        """
        Extract citation IDs such as:

            [1]
            [2]
            [5]

        from the generated answer.
        """

        matches = cls.CITATION_PATTERN.findall(
            answer
        )

        return [
            int(match)
            for match in matches
        ]

    # =========================================================
    # REMOVE INVALID CITATIONS
    # =========================================================

    def remove_invalid_citations(
        self,
        answer: str,
        citations: list[dict],
    ):
        """
        Remove citation markers from the answer when
        their IDs do not exist in the supplied citations.

        Example:

            Input:
                "Agentic AI is useful [1] [7]."

            If [1] exists and [7] doesn't:

                "Agentic AI is useful [1]."
        """

        available_ids = {
            citation["id"]
            for citation in citations
        }

        def replace(match):

            citation_id = int(
                match.group(1)
            )

            if citation_id in available_ids:
                return match.group(0)

            return ""

        cleaned_answer = (
            self.CITATION_PATTERN.sub(
                replace,
                answer,
            )
        )

        # Clean up accidental double spaces.
        cleaned_answer = re.sub(
            r" {2,}",
            " ",
            cleaned_answer,
        )

        return cleaned_answer.strip()